### ISSUE TITLE
Deprecation warning about `set-output`

### ISSUE THREAD

**Issue by mhucka** [JamieMagee/wayback#120]
Thank you for creating this action. When I run the version available in the GitHub Actions Marketplace (1.3.19), I get a deprecation warning:
```
The `set-output` command is deprecated and will be disabled soon. 
Please upgrade to using Environment Files. For more information see: 
https://github.blog/changelog/2022-10-11-github-actions-deprecating-save-state-and-set-output-commands/
```

In the workflow where I use this action, the warning is certainly due to invoking the `wayback` action, but I'm not sure if the source is the `wayback` action code itself, or from something that it calls.

**Comment by JamieMagee** [comment]
Thanks for the heads up. Can you share a link to your build logs please?

Also, the git tags in this repository are the source of truth. The marketplace listing is mostly for discoverability. Can you try with the latest tag `1.3.28`?

**Comment by mhucka** [comment]
I tried 1.3.28 and indeed the problem has gone away. Thanks for the PRs!

In case it's still relevant, attached here's a link to a past log before the change:

<https://pipelines.actions.githubusercontent.com/serviceHosts/d5296feb-b551-4b06-aca7-1ca231242c9b/_apis/pipelines/1/runs/33/signedlogcontent/2?urlExpires=2022-11-23T03%3A33%3A17.1178288Z&urlSigningMethod=HMACV1&urlSignature=Id6RZmwm%2BuDcblfrN6jxvbWJ0CYqR%2Big9obaFGlv4Uw%3D>
