### ISSUE TITLE
Error when running action

### ISSUE THREAD

**Issue by jonblatho** [JamieMagee/wayback#73]
I am receiving an "[Unable to fetch status](https://github.com/JamieMagee/wayback/blob/0e081fbbbfe2f52374c2e51e70b76bc123a3e4ab/src/wayback.ts#L51)" error when using this action. Pages are still being archived as expected, and one can get the URL by visiting the Wayback Machine website, but there's an issue with the response which is preventing the code from receiving the archive URL correctly.

**Comment by jonblatho** [comment]
Alright, the issue is that the job GUID no longer matches the format expected in the regex. While previously GUIDs were formatted as a regular UUID, they are now formatted like `spn2-6abe074d2183fee9619239b995f8e083d8f359ff-77b21449`.

Pull request coming shortly with updated regex and tests.

**Comment by 3raxton** [comment]
Hey there @jonblatho, I'm dealing with this again. Do you know what I could do to prevent this from happening?

**Comment by jonblatho** [comment]
@3raxton I happen to be experimenting with a fix right now. It looks to be another GUID format change (looks like the final nine characters have been removed). I'll keep you posted if I get it working.

**Comment by 3raxton** [comment]
Sounds great, thanks for the info. Looking forward to seeing what comes from it 🔥

**Comment by jonblatho** [comment]
@3raxton Just got a fix working in [jonblatho/wayback](https://github.com/jonblatho/wayback). If you need this _right now_, you can update your workflow to point there with the version set to `v1.3.19`, but @JamieMagee was quite responsive on my PR the last time, so it shouldn't be too long a wait for a fix on this repo.

**Comment by 3raxton** [comment]
Awesome, thanks for your hard work @jonblatho! It’s not something I need right now but I will be on the lookout in @JamieMagee’s workflow in the near future. Be well!
