### ISSUE TITLE
Is it possible to use Wayback with Gitlab?

### ISSUE THREAD

**Issue by iaeiou** [JamieMagee/wayback#77]
Hi there,

I would love to enjoy this tool, but I'm running a website hosted with Gitlab Pages.

Do you know if this is possible to use `wayback` (and especially the feature `saveOutlinks`) with Gitlab?

Thank you

**Comment by JamieMagee** [comment]
This action is designed for use with GitHub Actions. I've licensed it under the MIT license, so you can easily port it to whatever the GitLab CI equivalent is. I don't intend to do that, so I'll close this issue.
